server:
  port: 8088
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@127.0.0.1:1521/orcl
    username: system
    password: Hyj888888
  jpa:
    database: oracle
    properties.hibernate.dialect: org.hibernate.dialect.Oracle10gDialect
    hibernate.ddl-auto: validate
    show-sql: true
  thymeleaf:
#    prefix: classpath:/templates/
#    suffix: .html
    mode: html5
    servlet:
      content-type: text/html
    cache: false
  messages:
    basename: i18n.login
logging:
  config: classpath:logs/logback.xml
  level:
    root: info
#添加memcached
memcache:
  servers: 192.168.112.141:11211
  failover: true
  initConn: 10
  minConn: 20
  maxConn: 1000
  maintSleep: 50
  nagle: false
  socketTO: 3000
  aliveCheck: true