server:
  port: 8088
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@127.0.0.1:1521/orcl
    username: system
    password: Hyj888888
  jpa:
    database: oracle
    properties.hibernate.dialect: org.hibernate.dialect.Oracle10gDialect
    hibernate.ddl-auto: validate
    show-sql: true
  thymeleaf:
#    prefix: classpath:/templates/
#    suffix: .html
    mode: html5
    servlet:
      content-type: text/html
    cache: false

logging:
  config: classpath:logs/logback.xml
  level:
    root: info